ansible_python_interpreter: /usr/bin/python3
ansible_connection: ssh
# ansible_ssh_private_key_file: /home/ubuntu/.ssh/datascientest.pem
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
ansible_user: ubuntu
ansible_password: datascientest
ansible_port: 22