apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pgadmin-svc
    env: prod
  name: pgadmin-svc
  namespace: ic-group
spec:
  ports:
  - name: 5050-80
    port: 5050
    protocol: TCP
    targetPort: 80
  selector:
    app: pgadmin
  type: LoadBalancer
status:
  loadBalancer: {}
