services:
  web:
    image: odoo:17.0
    container_name: odoo-web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD=myodoo
    networks:
      - ic-network
  db:
    image: postgres:15
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - ic-network

volumes:
  odoo-web-data:
    name: odoo-web-data
  odoo-db-data:
    name: odoo-db-data
networks:
  ic-network:
    driver: bridge
    name: ic-network
    external: true

