services:
  ic-webapp:
    container_name: ic-webapp
    image: ghcr.io/ulrich-sun/ic-webapp:${VERSION:-1.0}
    ports:
      - "${IC_WEBAPP_PORT:-8080}:8080"
    environment:
      - ODOO_URL=${ODOO_URL:-https://www.odoo.com/}
      - PGADMIN_URL=${PGADMIN_URL:-https://www.pgadmin.org/}
    networks:
      - ${IC_NETWORK:-ic-network}

networks:
  ic-network:
    driver: bridge 
    name: ${IC_NETWORK:-ic-network}