apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-web-data
  namespace: ic-group
  labels:
    app: odoo-web
    env: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path