apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: odoo-db-svc
    env: prod
  name: odoo-db-svc
  namespace: ic-group
spec:
  ports:
  - name: 5432-5432
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: odoo-db
  type: ClusterIP
status:
  loadBalancer: {}
